# Baseline ResNet Training Configuration for CIFAR-10

# Model configuration
model:
  arch: "resnet18"  # resnet18, resnet34, resnet50
  num_classes: 10

# Data configuration
data:
  data_dir: "./data"
  batch_size: 128
  num_workers: 4
  download: true
  normalize: true

# Training configuration
training:
  epochs: 200
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  
  # Learning rate scheduler
  scheduler:
    type: "step"  # step, cosine
    step_size: 50
    gamma: 0.1

# Logging and saving
logging:
  log_interval: 100
  save_dir: "./checkpoints/baseline"
  save_every: 10

# Device configuration
device: "cuda"  # cuda, cpu, auto